# Maximum number of warnings before a player is kicked
maxWarnings: 3

# Limit on the number of packets that can be received per second per player
packetLimit: 250

# Message displayed when a player is kicked due to packet spam
kickMessage: "You have been kicked for sending too many packets!"
